### ISSUE TITLE
Addon is closing with an error upon execution.

### ISSUE THREAD

**Issue by igoryonya** [yasuyk/web-beautify#43]
When trying to apply on the unformatted html page:
M-x web-beautify-html
I get an error:
/usr/local/lib/node_modules/js-beautify/node_modules/minimatch/dist/cjs/index.js:192
    options;
           ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/js-beautify/node_modules/editorconfig/lib/index.js:33:21)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by igoryonya** [comment]
my system nodejs was older, then required.
